/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class adminreg extends java.awt.Frame {

    /**
     * Creates new form adminreg
     */
    public adminreg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        label4 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        label5 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label7 = new java.awt.Label();

        setBackground(new java.awt.Color(0, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label1.setText("Name");
        add(label1);
        label1.setBounds(120, 150, 110, 51);

        label2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label2.setText("Address");
        add(label2);
        label2.setBounds(120, 230, 130, 50);

        label3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label3.setText("Contact");
        add(label3);
        label3.setBounds(120, 290, 140, 51);

        textField1.setBackground(new java.awt.Color(204, 204, 204));
        textField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        add(textField1);
        textField1.setBounds(300, 160, 190, 40);

        textField2.setBackground(new java.awt.Color(204, 204, 204));
        textField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        add(textField2);
        textField2.setBounds(300, 230, 190, 40);

        textField3.setBackground(new java.awt.Color(204, 204, 204));
        add(textField3);
        textField3.setBounds(300, 300, 190, 40);

        label4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label4.setText("Email");
        add(label4);
        label4.setBounds(120, 360, 110, 50);

        textField4.setBackground(new java.awt.Color(204, 204, 204));
        textField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField4ActionPerformed(evt);
            }
        });
        add(textField4);
        textField4.setBounds(300, 370, 190, 40);

        label5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label5.setText("Password");
        add(label5);
        label5.setBounds(120, 440, 160, 51);

        textField5.setBackground(new java.awt.Color(204, 204, 204));
        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });
        add(textField5);
        textField5.setBounds(300, 450, 190, 40);

        button1.setBackground(new java.awt.Color(102, 102, 102));
        button1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button1.setLabel("Register");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(260, 560, 100, 70);

        label7.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        label7.setText("Admin Reg");
        add(label7);
        label7.setBounds(180, 40, 230, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    private void textField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField4ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
        
        try
        {
            String name,address,contact,email,password;
           
            name=textField1.getText();
            address=textField2.getText();
            contact=textField3.getText();
            email=textField4.getText();
            password=textField5.getText();
            Class.forName("com.mysql.jdbc.Driver");
            String path="jdbc:mysql://localhost:3306/warehouse";
            String dbuser="root";
            String dbpassword="";
            
            Connection cn= DriverManager.getConnection(path,dbuser,dbpassword);
            String sql_insert="insert into admindata values(?,?,?,?,?)";
            PreparedStatement p2= cn.prepareStatement(sql_insert);
            p2.setString(1,name);
            p2.setString(2,address);
            p2.setString(3,contact);
            p2.setString(4,email);
            p2.setString(5,password);
             int a=p2.executeUpdate();
             if(a==1)
             {
                 JOptionPane.showMessageDialog(null,"Data saved");
                 
             }
             else
             {
                 JOptionPane.showMessageDialog(null,"Cannot save Data");
             }
             textField1.setText("");
             textField2.setText("");
             textField3.setText("");
             textField4.setText("");
             textField5.setText("");
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null,""+e);
        }
        
        
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminreg().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label7;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    // End of variables declaration//GEN-END:variables
}
