/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author DELL
 */
public class Grain extends java.awt.Frame {

    /**
     * Creates new form Grain
     */
    public Grain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        button1 = new java.awt.Button();

        setBackground(new java.awt.Color(153, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setText("Name");
        add(label1);
        label1.setBounds(100, 210, 110, 40);

        label2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label2.setText("Type");
        add(label2);
        label2.setBounds(100, 310, 89, 51);

        label3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label3.setText("Description");
        add(label3);
        label3.setBounds(100, 420, 198, 70);

        textArea1.setBackground(new java.awt.Color(255, 255, 255));
        textArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(textArea1);
        textArea1.setBounds(410, 440, 290, 90);

        textField1.setBackground(new java.awt.Color(255, 255, 255));
        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        add(textField1);
        textField1.setBounds(400, 210, 290, 40);

        textField2.setBackground(new java.awt.Color(255, 255, 255));
        textField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        add(textField2);
        textField2.setBounds(400, 310, 290, 40);

        button1.setBackground(new java.awt.Color(51, 51, 51));
        button1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        button1.setLabel("ADD");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(100, 550, 90, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try
        {
            String name,type,des;
            int qty=0;
            name=textField1.getText();
            type=textField2.getText();
            des=textArea1.getText();
            Class.forName("com.mysql.jdbc.Driver");
            String path="jdbc:mysql://localhost:3306/warehouse";
            String dbuser="root";
            String dbpassword="";
            
            Connection cn= DriverManager.getConnection(path,dbuser,dbpassword);
            String sql_insert="insert into graindata values(?,?,?,?)";
            PreparedStatement p2= cn.prepareStatement(sql_insert);
            p2.setString(1,name);
            p2.setString(2,type);
            p2.setString(3,des);
            p2.setInt(4,qty);
             int a=p2.executeUpdate();
             if(a==1)
             {
                 javax.swing.JOptionPane.showMessageDialog(null,"Data saved");
                 
             }
             else
             {
                 javax.swing.JOptionPane.showMessageDialog(null,"Cannot save Data");
             }
             textArea1.setText("");
             textField1.setText("");
             textField2.setText("");
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null,""+e);
        }
    }//GEN-LAST:event_button1ActionPerformed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grain().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
