/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class IssueGrain extends java.awt.Frame {

    /**
     * Creates new form IssueGrain
     */
    public IssueGrain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        label4 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label5 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        label6 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();

        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Grain");
        add(label1);
        label1.setBounds(330, 170, 80, 36);

        textField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        add(textField1);
        textField1.setBounds(540, 170, 250, 40);

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("Type");
        add(label2);
        label2.setBounds(330, 250, 70, 36);

        textField2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        add(textField2);
        textField2.setBounds(540, 250, 250, 50);

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("Description");
        add(label3);
        label3.setBounds(320, 360, 140, 36);

        textArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(textArea1);
        textArea1.setBounds(540, 340, 260, 80);

        label4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label4.setText("Qty");
        add(label4);
        label4.setBounds(330, 460, 43, 36);

        textField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        add(textField3);
        textField3.setBounds(540, 470, 260, 40);

        label5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label5.setText("New Qty");
        add(label5);
        label5.setBounds(320, 560, 110, 36);

        textField4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        add(textField4);
        textField4.setBounds(540, 560, 270, 40);

        label6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label6.setText("Remark");
        add(label6);
        label6.setBounds(330, 650, 90, 36);

        textField5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(textField5);
        textField5.setBounds(540, 650, 270, 40);

        button2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button2.setLabel("Cancel");
        add(button2);
        button2.setBounds(550, 730, 140, 32);

        button3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button3.setLabel("Issue");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(310, 730, 110, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        try{
        String name,type,description,date,remark;
        int qty;
        name=textField1.getText();
        type=textField2.getText();
        description=textArea1.getText();
        qty=Integer.parseInt(textField3.getText());
        date=textField4.getText();
        remark=textField5.getText();
        
        Class.forName("com.mysql.jdbc.Driver");
        //String id=JOptionPane.showInputDialog(null,"enter id");
        String path="jdbc:mysql://localhost:3306/warehouse";
        String dbuser="root";
        String dbpassword="";
        Connection cn=DriverManager.getConnection(path,dbuser,dbpassword);

        String sql_insert="update grain_data set qty=qty-? where type=?";

        PreparedStatement p2=cn.prepareStatement(sql_insert);
        p2.setInt(1,qty);
        p2.setString(2,type);
        //p2.setString(3,description);
        //p2.setInt(4,qty);
        //p2.setString(5,date);
        //p2.setString(6,remark);
        int a=p2.executeUpdate();
        if(a==1)
        {
            JOptionPane.showMessageDialog(null,""+qty+" Kgs wheat issued succesfully");
        }else
        {
            JOptionPane.showMessageDialog(null,"Try Again");
        }   
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueGrain().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    // End of variables declaration//GEN-END:variables
}
