/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package w1;

/**
 *
 * @author DELL
 */
public class Login extends java.awt.Panel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label1.setText("Login");
        add(label1);
        label1.setBounds(510, 30, 100, 70);

        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setText("Email");
        add(label2);
        label2.setBounds(260, 180, 100, 28);

        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setText("Password");
        add(label3);
        label3.setBounds(270, 280, 83, 28);

        textField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(textField1);
        textField1.setBounds(500, 170, 150, 28);

        textField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(textField2);
        textField2.setBounds(510, 280, 140, 28);

        button1.setLabel("Enter");
        add(button1);
        button1.setBounds(250, 410, 90, 24);

        button2.setLabel("Exit");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(540, 410, 80, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    java.awt.Button button1;
    java.awt.Button button2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    java.awt.TextField textField1;
    java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
