/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package w1;

/**
 *
 * @author DELL
 */
public class Welcome extends java.awt.Panel {

    /**
     * Creates new form welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        label1.setText("Welcome to Warehouse");
        add(label1);
        label1.setBounds(300, 110, 710, 60);

        label2.setFont(new java.awt.Font("Dialog", 2, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 51, 153));
        label2.setText("By anisha deepshikha ayushi");
        add(label2);
        label2.setBounds(350, 210, 520, 220);

        button1.setBackground(new java.awt.Color(153, 153, 153));
        button1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        button1.setLabel("Enter");
        add(button1);
        button1.setBounds(330, 540, 120, 50);

        button2.setBackground(new java.awt.Color(153, 153, 153));
        button2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        button2.setLabel("Exit");
        add(button2);
        button2.setBounds(730, 530, 140, 55);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    java.awt.Button button1;
    java.awt.Button button2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
